### ISSUE TITLE
Camera Pose

### ISSUE THREAD

**Issue by smoothumut** [rasmushaugaard/6d-pose-annotator#1]
Hi Rasmus, thanks for the surfemb and this great labeling tool.
In this project, what is the camera_pose in scene.json. You say it is camera extrinsics but I couldnt understand how? 
what are the components in camera_pose
Thanks in advance
Best Regards

**Comment by rasmushaugaard** [comment]
Hi 
The first three parameters are the position. The last three make up the rotation vector.
BR Rasmus

**Comment by smoothumut** [comment]
Thank you very much Rasmus, So the rotation vector is direction vector of camera where it looks up. am I right?
Note: I am new on 3d, sorry for that :)

**Comment by rasmushaugaard** [comment]
Rotation vector is a rotation representation. You can use [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html) to convert between representations.
